# 📝 Advanced NumPy — Assignment

**Instructions**

- Solve every question using NumPy only — no Python `for` loops unless a question explicitly allows one.
- Where a question asks you to predict something first, write the prediction as a comment before running the code.
- Print the shape of your result whenever an answer involves reshaping, stacking or matrix multiplication.
- Searching the documentation is allowed and encouraged.

In [1]:
import numpy as np


### Q1.

A class has 4 students and 3 subjects. Their marks are given below. The examiner announces a subject-wise bonus of 5, 2 and 8 marks respectively. Add the bonus to every student in one line using broadcasting, then cap any mark above 100 back to 100 and report how many marks had to be capped.

```python
marks = np.array([[88, 96, 95],
                  [72, 99, 91],
                  [98, 85, 97],
                  [60, 75, 80]])
```

In [2]:
# Q1
marks = np.array([[88, 96, 95],
                  [72, 99, 91],
                  [98, 85, 97],
                  [60, 75, 80]])

bonus = np.array([5, 2, 8])
marks = marks+bonus

capped = marks>100
print(np.where(capped, 100, marks))
print("Capped:", np.sum(capped))


[[ 93  98 100]
 [ 77 100  99]
 [100  87 100]
 [ 65  77  88]]
Capped: 4


### Q2.

Create a 5x5 matrix with a border of 1s and 0s inside, without writing the matrix out by hand.

In [3]:
# Q2
a = np.ones((5, 5), dtype=int)
a[1:-1, 1:-1] = 0
print(a)


[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


### Q3.

Without running the code, predict the shape of `np.arange(30).reshape(5, -1).T`. Write your prediction as a comment, then verify it. Also explain in a comment why `np.arange(30).reshape(4, -1)` fails.

In [4]:
# Q3
a = np.arange(30).reshape(5, -1).T
print(a.shape)

(6, 5)


### Q4.

Two arrays of size 4 are given. First join them with `hstack` and print the shape. Then, using the same two arrays, build a proper (4, 2) two-column table. In a comment, state why the first attempt did not produce two columns.

```python
heights = np.array([172, 158, 181, 166])
weights = np.array([68, 52, 84, 59])
```

In [5]:
# Q4
heights = np.array([172, 158, 181, 166])
weights = np.array([68, 52, 84, 59])

a = np.hstack((heights, weights))
print(a)
print(a.shape)

b = np.column_stack((heights, weights))
print(b)
print(b.shape)

[172 158 181 166  68  52  84  59]
(8,)
[[172  68]
 [158  52]
 [181  84]
 [166  59]]
(4, 2)


### Q5.

Given a 1D array of 12 monthly sales figures, reshape it into 4 quarters of 3 months each and find which quarter (index) had the highest average sales, along with that average.

```python
sales = np.array([120, 135, 98, 160, 175, 190, 88, 92, 105, 210, 198, 230])
```

In [6]:
# Q5
sales = np.array([120, 135, 98, 160, 175, 190, 88, 92, 105, 210, 198, 230])

quarters = sales.reshape(4, 3)
avg = quarters.mean(axis=1)

print(quarters)
print("Averages:", avg)
print("Highest quarter index:", np.argmax(avg))
print("Highest average:", avg.max())


[[120 135  98]
 [160 175 190]
 [ 88  92 105]
 [210 198 230]]
Averages: [117.66666667 175.          95.         212.66666667]
Highest quarter index: 3
Highest average: 212.66666666666666


### Q6.

Build a 3x3 multiplication table from the array below using broadcasting only. Do not use loops and do not use `np.outer` — reshape one of the operands so that broadcasting produces the grid.

```python
a = np.array([2, 3, 4])
```

In [7]:
# Q6
a = np.array([2, 3, 4])

table = a.reshape(-1, 1)*a
print(table)


[[ 4  6  8]
 [ 6  9 12]
 [ 8 12 16]]


### Q7.

Create an array of numbers from 1 to 20 and replace every multiple of 3 with -1.

In [8]:
# Q7
a = np.arange(1, 21)
a[a%3==0] = -1
print(a)


[ 1  2 -1  4  5 -1  7  8 -1 10 11 -1 13 14 -1 16 17 -1 19 20]


### Q8.

For the matrix below, scale every column into the 0 to 1 range using column-wise min-max normalization `(x - col_min) / (col_max - col_min)`. Use broadcasting only — no loops. Verify that each column of the result has a minimum of 0 and a maximum of 1.

```python
X = np.array([[ 50, 1200,  3],
              [ 80, 1500,  9],
              [ 65,  900,  5],
              [ 95, 2000,  7]])
```

In [9]:
# Q8
X = np.array([[50, 1200, 3],
              [80, 1500, 9],
              [65, 900, 5],
              [95, 2000, 7]])

col_min = X.min(axis=0)
col_max = X.max(axis=0)

result = (X-col_min)/(col_max-col_min)

print(result)
print("Column mins:", result.min(axis=0))
print("Column maxs:", result.max(axis=0))


[[0.         0.27272727 0.        ]
 [0.66666667 0.54545455 1.        ]
 [0.33333333 0.         0.33333333]
 [1.         1.         0.66666667]]
Column mins: [0. 0. 0.]
Column maxs: [1. 1. 1.]


### Q9.

Award medals to the scores below using nested `np.where`: 'Gold' for 90 and above, 'Silver' for 75 and above, 'Bronze' for 60 and above, and 'None' otherwise. Then count how many students received each medal.

```python
scores = np.array([94, 61, 77, 45, 90, 88, 59, 72])
```

In [10]:
# Q9
scores = np.array([94, 61, 77, 45, 90, 88, 59, 72])

medals = np.where(scores>=90, "Gold",
                  np.where(scores>=75, "Silver",
                           np.where(scores>=60, "Bronze", "None")))

print(medals)
print("Gold:", np.sum(medals=="Gold"))
print("Silver:", np.sum(medals=="Silver"))
print("Bronze:", np.sum(medals=="Bronze"))
print("None:", np.sum(medals=="None"))


['Gold' 'Bronze' 'Silver' 'None' 'Gold' 'Silver' 'None' 'Bronze']
Gold: 2
Silver: 2
Bronze: 2
None: 2


### Q10.

Given the matrix below, use `np.where` with a single condition to obtain the row and column indices of every element greater than 50, print those elements, and then replace them with 0 in a copy of the matrix while leaving the original untouched.

```python
m = np.array([[10, 80, 45],
              [55, 20, 99],
              [70, 33, 12]])
```

In [11]:
# Q10
m = np.array([[10, 80, 45],
              [55, 20, 99],
              [70, 33, 12]])

rows, cols = np.where(m > 50)
print("Rows:", rows)
print("Columns:", cols)
print("Elements:", m[rows, cols])

new_m = m.copy()
new_m[m > 50] = 0

print(new_m)
print(m)


Rows: [0 1 1 2]
Columns: [1 0 2 0]
Elements: [80 55 99 70]
[[10  0 45]
 [ 0 20  0]
 [ 0 33 12]]
[[10 80 45]
 [55 20 99]
 [70 33 12]]


### Q11.

Three sensors each recorded 5 readings. Stack them so that each sensor becomes a row, and separately stack them so that each sensor becomes a column. Print both shapes and confirm that one is the transpose of the other.

```python
s1 = np.array([12, 15, 11, 19, 14])
s2 = np.array([22, 18, 25, 21, 20])
s3 = np.array([31, 35, 29, 33, 30])
```

In [12]:
# Q11
s1 = np.array([12, 15, 11, 19, 14])
s2 = np.array([22, 18, 25, 21, 20])
s3 = np.array([31, 35, 29, 33, 30])

rows = np.vstack((s1, s2, s3))
cols = np.column_stack((s1, s2, s3))

print(rows)
print(rows.shape)
print(cols)
print(cols.shape)
print(np.array_equal(rows.T, cols))


[[12 15 11 19 14]
 [22 18 25 21 20]
 [31 35 29 33 30]]
(3, 5)
[[12 22 31]
 [15 18 35]
 [11 25 29]
 [19 21 33]
 [14 20 30]]
(5, 3)
True


### Q12.

Create a random 6x6 matrix with `seed = 1` and values between 1 and 100, then find the row-wise maximum and the column-wise minimum.

In [13]:
# Q12
np.random.seed(1)
a = np.random.randint(1, 101, (6, 6))

print(a)
print("Row max:", a.max(axis=1))
print("Column min:", a.min(axis=0))


[[38 13 73 10 76  6]
 [80 65 17  2 77 72]
 [ 7 26 51 21 19 85]
 [12 29 30 15 51 69]
 [88 88 95 97 87 14]
 [10  8 64 62 23 58]]
Row max: [76 80 85 69 97 64]
Column min: [ 7  8 17  2 19  6]


### Q13.

A and B are both 2x3 matrices. Compute `A @ B.T` and `A.T @ B`. Print the shape of each result and explain in a comment why both multiplications are legal while `A @ B` is not.

```python
A = np.array([[1, 2, 3],
              [4, 5, 6]])
B = np.array([[7, 8, 9],
              [1, 0, 2]])
```

In [14]:
# Q13
A = np.array([[1, 2, 3],
              [4, 5, 6]])
B = np.array([[7, 8, 9],
              [1, 0, 2]])

x = A @ B.T
y = A.T @ B

print(x)
print(x.shape)
print(y)
print(y.shape)

[[ 50   7]
 [122  16]]
(2, 2)
[[11  8 17]
 [19 16 28]
 [27 24 39]]
(3, 3)


### Q14.

Build a complete multi-step pipeline. Starting from the two arrays below: convert them into column vectors, join them into a single two-column table, attach a third column holding each row's total, then multiply the three-column table by `w = [0.5, 0.2, 0.3]` to obtain one score per row. Finally use `np.where` to mark each score as 1 if it is above the average score and 0 otherwise. Report the shape of every intermediate array.

```python
hours = np.array([2, 8, 5, 10, 3, 7])
attendance = np.array([55, 92, 70, 98, 60, 85])
```

In [15]:
# Q14
hours = np.array([2, 8, 5, 10, 3, 7])
attendance = np.array([55, 92, 70, 98, 60, 85])

h = hours.reshape(-1, 1)
a = attendance.reshape(-1, 1)
print("hours:", h.shape)
print("attendance:", a.shape)

table = np.hstack((h, a))
print(table)
print("table:", table.shape)

total = table.sum(axis=1, keepdims=True)
table = np.hstack((table, total))
print(table)
print("with total:", table.shape)

w = np.array([0.5, 0.2, 0.3])
scores = table @ w
print(scores)
print("scores:", scores.shape)

avg = scores.mean()
result = np.where(scores > avg, 1, 0)
print(result)
print("result:", result.shape)


hours: (6, 1)
attendance: (6, 1)
[[ 2 55]
 [ 8 92]
 [ 5 70]
 [10 98]
 [ 3 60]
 [ 7 85]]
table: (6, 2)
[[  2  55  57]
 [  8  92 100]
 [  5  70  75]
 [ 10  98 108]
 [  3  60  63]
 [  7  85  92]]
with total: (6, 3)
[29.1 52.4 39.  57.  32.4 48.1]
scores: (6,)
[0 1 0 1 0 1]
result: (6,)


### Q15.

Apply min-max normalization to scale any array into the 0 to 1 range using `(x - min) / (max - min)`.

In [16]:
# Q15
a = np.array([10, 20, 30, 40, 50])
result = (a - a.min()) / (a.max() - a.min())
print(result)


[0.   0.25 0.5  0.75 1.  ]


### Q16.

Take the array below and create two 1D versions of it — one with `flatten()` and one with `ravel()`. Change the first element of each, then print the original matrix. Explain the difference you observe in a comment.

```python
m = np.array([[4, 8, 15],
              [16, 23, 42]])
```

In [17]:
# Q16
m = np.array([[4, 8, 15],
              [16, 23, 42]])
a = m.flatten()
b = m.ravel()
a[0] = 999
b[0] = 888

print(a)
print(b)
print(m)

[999   8  15  16  23  42]
[888   8  15  16  23  42]
[[888   8  15]
 [ 16  23  42]]


### Q17.

28 daily temperature readings are given. Reshape them into 4 weeks of 7 days, then: find each week's average, identify the hottest week, and count how many individual days crossed 35 degrees.

```python
np.random.seed(7)
temps = np.random.randint(15, 41, 28)
```

In [18]:
# Q17
np.random.seed(7)
temps = np.random.randint(15, 41, 28)

weeks = temps.reshape(4, 7)
avg = weeks.mean(axis=1)
hot_week = np.argmax(avg)
hot_days = np.sum(temps > 35)

print(weeks)
print("Weekly averages:", avg)
print("Hottest week index:", hot_week)
print("Days above 35:", hot_days)


[[30 19 40 37 18 34 38]
 [22 40 29 38 23 40 29]
 [25 23 22 21 19 31 22]
 [27 15 26 38 21 34 27]]
Weekly averages: [30.85714286 31.57142857 23.28571429 26.85714286]
Hottest week index: 1
Days above 35: 7


### Q18.

Create two random 3x3 matrices A and B, compute `A @ B` and `B @ A`, and check whether the two results are equal. State your conclusion about matrix multiplication in a comment.

In [19]:
# Q18
np.random.seed(1)
A = np.random.randint(1, 10, (3, 3))
B = np.random.randint(1, 10, (3, 3))

x = A @ B
y = B @ A

print(A)
print(B)
print(x)
print(y)
print(np.array_equal(x, y))

[[6 9 6]
 [1 1 2]
 [8 7 3]]
[[5 6 3]
 [5 3 5]
 [8 8 2]]
[[123 111  75]
 [ 26  25  12]
 [ 99  93  65]]
[[60 72 51]
 [73 83 51]
 [72 94 70]]
False


### Q19.

Given the marks matrix below (5 students x 4 subjects), first replace every mark below 35 with 35, then compute each student's total, and finally print the index of the topper along with their total.

```python
marks = np.array([[45, 28, 67, 80],
                  [33, 90, 55, 41],
                  [72, 66, 30, 58],
                  [88, 79, 91, 84],
                  [25, 40, 38, 52]])
```

In [20]:
# Q19
marks = np.array([[45, 28, 67, 80],
                  [33, 90, 55, 41],
                  [72, 66, 30, 58],
                  [88, 79, 91, 84],
                  [25, 40, 38, 52]])
marks[marks < 35] = 35
total = marks.sum(axis=1)
topper = np.argmax(total)

print(marks)
print("Totals:", total)
print("Topper index:", topper)
print("Topper total:", total[topper])


[[45 35 67 80]
 [35 90 55 41]
 [72 66 35 58]
 [88 79 91 84]
 [35 40 38 52]]
Totals: [227 221 231 342 165]
Topper index: 3
Topper total: 342


### Q20.

Start from `arr = np.arange(1, 11)`. Create one variable using a plain slice `arr[2:6]` and another using `arr[2:6].copy()`. Change the first element of each to 999, then print the original array and explain in a comment which change survived and why.

In [21]:
# Q20
arr = np.arange(1, 11)
a = arr[2:6]
b = arr[2:6].copy()
a[0] = 999
b[0] = 999
print(arr)

[  1   2 999   4   5   6   7   8   9  10]


### Q21.

Explore `np.diag` in the NumPy documentation and use it to extract the diagonal of a 4x4 matrix. Then use the same function in its second role — to build a diagonal matrix from a 1D array.

In [22]:
# Q21
m = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12],
              [13, 14, 15, 16]])
print(np.diag(m))

a = np.array([10, 20, 30, 40])
print(np.diag(a))


[ 1  6 11 16]
[[10  0  0  0]
 [ 0 20  0  0]
 [ 0  0 30  0]
 [ 0  0  0 40]]


---

**Before you submit:** re-run the notebook from top to bottom and make sure every cell executes without errors.