In [ ]:
import numpy as np


In [ ]:
import numpy as np

x = np.array([[1,2,3],[4,5,6]])
y = np.array([[3.5],[5],[6]])
print(x)
print(x.T)
print(x@x.T)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]
[[14 32]
 [32 77]]


In [ ]:
s1 = [72, 85, 60, 91]
s2 = [45, 30, 98, 55]
s3 = [88, 66, 74, 100]

old = np.array([['62', '71', '55', '80'],
                ['49', '58', '66', '73']])

In [ ]:
s1 = [72, 85, 60, 91]
s2 = [45, 30, 98, 55]
s3 = [88, 66, 74, 100]

old = np.array([['62', '71', '55', '80'],
                ['49', '58', '66', '73']])


table = np.array([s1,s2,s3])
print(table)
print(f"total no of marks entriess", table.size)
print(f"no of students {table.shape[0]} no of subjext {table.shape[1]}")
old = old.astype('int32')
print(np.sum(old,axis=1))
print(table.astype(float))
print(np.vstack((table,old)))

[[ 72  85  60  91]
 [ 45  30  98  55]
 [ 88  66  74 100]]
total no of marks entriess 12
no of students 3 no of subjext 4
[268 246]
[[ 72.  85.  60.  91.]
 [ 45.  30.  98.  55.]
 [ 88.  66.  74. 100.]]
[[ 72  85  60  91]
 [ 45  30  98  55]
 [ 88  66  74 100]
 [ 62  71  55  80]
 [ 49  58  66  73]]
