In [3]:
import numpy as np

# NumPy Practice Session

Quick one-line recaps only — the focus here is practice. For each topic, solve the questions in the empty code cells provided.


## 1. Array Creation Basics

_`np.array(list)` → from list | `np.zeros(shape)` → all 0s | `np.ones(shape)` → all 1s | `np.full(shape, val)` → custom value | `np.arange(start,stop,step)` → like range()_


**Q1.1** Create a 1D array of 6 numbers of your choice.

In [4]:
# Write your code here
arr = np.array([1,2,3,4,5])

**Q1.2** Create a 3x3 array of zeros and a 2x2 array filled with the value 7.

In [7]:
# Write your code here
a = np.zeros((3,3))
print(a)
b = np.full((2,2),7)
print(b)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[7 7]
 [7 7]]


**Q1.3** Create an array of odd numbers from 1 to 21 using `arange`.

In [9]:
# Write your code here
a = np.arange(1,22,2)
print(a)

[ 1  3  5  7  9 11 13 15 17 19 21]


## 2. Advanced Creation

_`.reshape(r,c)` → change shape | `np.linspace(start,stop,num)` → num evenly spaced values | `np.eye(n)` → n×n identity matrix_


**Q2.1** Create numbers 0 to 11 using `arange` and reshape into a 3x4 matrix.

In [11]:
# Write your code here
a = np.arange(0,12)
print(a)
a = a.reshape(3,4)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


**Q2.2** Generate 7 evenly spaced values between 10 and 50 using `linspace`.

In [13]:
# Write your code here
a = np.linspace(10,51,7)
print(a)

[10.         16.83333333 23.66666667 30.5        37.33333333 44.16666667
 51.        ]


**Q2.3** Create a 5x5 identity matrix.

In [21]:
# Write your code here
a = np.eye(5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


## 3. Array Attributes

_`.shape` → dimensions tuple | `.ndim` → no. of dimensions | `.size` → total elements | `.dtype` → data type_


**Q3.1** Create a (4,3) array and print its shape, ndim, size, and dtype.

In [19]:
# Write your code here
a = np.arange(1,13).reshape(4,3)
print(a)
print(a.shape)
print(a.ndim)
print(a.size)
print(a.dtype)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
(4, 3)
2
12
int64


**Q3.2** Create a (3,) vector and check if it's compatible for a dot product with a (5,3) matrix.

In [22]:
# Write your code here
a = np.array([1,2,3])
b = np.arange(1,16).reshape(5,3)
print(a@b)


ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 5 is different from 3)

## 4. Indexing & Slicing

_`arr[i]` / `arr[r,c]` → access | `arr[a:b, c:d]` → sub-matrix | `arr[::step]` → step slicing | `arr[::-1]` → reverse_


**Q4.1** Create a 4x4 array with values 1-16. Extract row 2, column 3.

In [23]:
# Write your code here
a = np.arange(1,17).reshape(4,4)
print(a[2,3])

12


**Q4.2** From the same array, extract the sub-matrix of the first two rows and last two columns.

In [24]:
# Write your code here
print(a[:2,2:])

[[3 4]
 [7 8]]


**Q4.3** Reverse the array row-wise, then column-wise.

In [ ]:
# Write your code here
print(a[:,::-1])        #row-wiaw
print(a[::-1])          #col-wise


[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]
 [16 15 14 13]]
[[13 14 15 16]
 [ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


**Q4.4** Print every 3rd element of a 1-20 array.

In [30]:
# Write your code here
a = np.arange(1,21)
print(a[::2])

[ 1  3  5  7  9 11 13 15 17 19]


## 5. Data Types & Coercion

_Mixed types auto-upcast to one common dtype | `.astype(type)` → explicit conversion_


**Q5.1** Create an array mixing ints and floats — check the resulting dtype.

In [33]:
# Write your code here
a = np.array([1,2,3,4.9,7.7,4.20])
print(a.dtype)

float64


**Q5.2** Convert a float array [1.9, 2.5, 3.1] to integers using astype.

In [36]:
# Write your code here
a = np.array([1.5,2.7,3.3,4.9,7.7,4.20])
print(a.astype("int32"))

[1 2 3 4 7 4]


## 6. Vectorized Arithmetic & Boolean Masking

_`a + b`, `a * b`, `a ** 2` → element-wise ops | `arr[arr > x]` → boolean filtering_


**Q6.1** Create two same-size arrays and compute their sum, product, and squares.

In [38]:
# Write your code here
a = np.arange(1,11)
b = np.arange(11,21)
print(a+b)
print(a*b)
print(a**2)
print(b[b>15])

[12 14 16 18 20 22 24 26 28 30]
[ 11  24  39  56  75  96 119 144 171 200]
[  1   4   9  16  25  36  49  64  81 100]
[16 17 18 19 20]


**Q6.2** Create an array of 10 random-looking numbers of your choice, then filter out only values greater than 15 using a boolean mask.

In [39]:
# Write your code here
a = np.arange(9,23)
print(a[a>15])

[16 17 18 19 20 21 22]


## 7. Random Module

_`np.random.seed(n)` → reproducibility | `.rand()` → uniform | `.randn()` → normal | `.randint(low,high,size)` → random ints | `.choice(arr,size)` → random sample | `.shuffle(arr)` → shuffle in place_


**Q7.1** Set a seed, generate a 3x3 uniform random array, and confirm reproducibility by rerunning with the same seed.

In [9]:
# Write your code here
np.random.seed(3)
np.random.rand(9).reshape(3,3)

array([[0.5507979 , 0.70814782, 0.29090474],
       [0.51082761, 0.89294695, 0.89629309],
       [0.12558531, 0.20724288, 0.0514672 ]])

**Q7.2** Generate 5 values from a normal distribution and 5 random integers between 1-100.

In [11]:
# Write your code here
np.random.randint(1,100,5)

array([97, 21, 45, 94, 40])

**Q7.3** Randomly pick 3 values (no repeats) from a list of 8 items, then shuffle a 1-10 array.

In [22]:
# Write your code here
lis = np.arange(8)
print(lis)
np.random.choice(lis,3)
print()
lis2 = np.arange(10)
np.random.shuffle(lis2)
print(lis2)

[0 1 2 3 4 5 6 7]

[7 3 2 8 6 4 1 9 0 5]


## 8. Reduction & Axis Rules

_`.sum()` / `.mean()` / `np.median()` → aggregations | `axis=0` → column-wise | `axis=1` → row-wise_


**Q8.1** Create a 3x3 matrix. Find the total sum, sum along axis=0, sum along axis=1.

In [26]:
# Write your code here
lis = np.arange(9).reshape(3,3)
total =np.sum(lis)
axix0 = np.sum(lis,axis=0)
axix1 = np.sum(lis,axis=1)

print(total)
print(axix0)
print(axix1)


36
[ 9 12 15]
[ 3 12 21]


**Q8.2** Find the mean and median of the same matrix.

In [27]:
# Write your code here
print(np.median(lis))
print(np.mean(lis))

4.0
4.0


## 9. Broadcasting

_Shapes match if equal or one of them is 1 (compared right to left) | smaller array auto-expands to fit_


**Q9.1** Add a (3,3) ones matrix with a 1D array of length 3 — observe the broadcast.

In [34]:
# Write your code here
a = np.ones((3,3)).astype("int32")
b = np.arange(3)
print(a+b)



[[1 2 3]
 [1 2 3]
 [1 2 3]]


**Q9.2** Create a row vector (1,3) and column vector (3,1), add them, and check the resulting shape.

In [35]:
# Write your code here
lis1 = np.arange(3).reshape(3,1)
lis2 = np.arange(3).reshape(1,3)
print(lis1+lis2)

[[0 1 2]
 [1 2 3]
 [2 3 4]]


## 10. Reshaping & Dimension Expansion

_`reshape(-1, n)` → auto-calculate the other dimension | `arr[np.newaxis, :]` → row vector | `arr[:, np.newaxis]` → column vector_


**Q10.1** Create a 12-element array and reshape it using -1 so it has 4 columns.

In [38]:
# Write your code here
a = np.arange(12).reshape(3, -1)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


**Q10.2** Take a 3-element 1D array and convert it into a row vector and a column vector using np.newaxis.

In [40]:
# Write your code here
a = np.arange(3)
print(a[np.newaxis, :])
print(a[ : ,np.newaxis])

[[0 1 2]]
[[0]
 [1]
 [2]]


## 11. Flatten vs Ravel

_`.flatten()` → returns a copy (original safe) | `.ravel()` → returns a view (original can change too)_


**Q11.1** Create a 2D array, flatten it with both methods, modify the first element of each result, and check which one affects the original array.

In [ ]:
# Write your code here
a = np.arange(4).reshape(2,2)
b = a.flatten()
b[0] = 12
print(b)
print(a)
c = a.ravel()
c[0] = 15
print(c)
print(a)

[12  1  2  3]
[[0 1]
 [2 3]]
[15  1  2  3]
[[15  1]
 [ 2  3]]


## 12. Stacking & Concatenation

_`np.vstack()` → stack rows | `np.hstack()` → stack columns | `np.concatenate(axis=)` → general version_


**Q12.1** Create two 2x2 arrays. Combine them using vstack, hstack, and concatenate on both axis=0 and axis=1.

In [54]:
# Write your code here
a = np.arange(4).reshape(2,2)
b = np.arange(3,7).reshape(2,2)
print(np.vstack((a,b)))
print(np.hstack((a,b)))
print(np.concatenate((a,b),axis=0))
print(np.concatenate((a,b),axis=1))

[[0 1]
 [2 3]
 [3 4]
 [5 6]]
[[0 1 3 4]
 [2 3 5 6]]
[[0 1]
 [2 3]
 [3 4]
 [5 6]]
[[0 1 3 4]
 [2 3 5 6]]


## 13. np.where — Conditional Logic

_`np.where(cond, a, b)` → element-wise if/else | `np.where(cond)` → returns matching indices_


**Q13.1** Create a 6-element array. Label each value 'High' or 'Low' based on a threshold using np.where.

In [56]:
# Write your code here
a = np.arange(6)
b = np.where(a>3, "High", "Low")
print(b)

['Low' 'Low' 'Low' 'Low' 'High' 'High']


**Q13.2** Use np.where (without true/false args) to find the indices of values above that threshold.

In [58]:
# Write your code here
b = np.where(a>3)
print(b)

(array([4, 5]),)


## 14. Matrix Operations & Transpose

_`*` → element-wise multiply | `@` / `np.dot()` → matrix multiplication | `.T` → transpose (rows ↔ cols)_


**Q14.1** Create two 2x2 matrices. Compute their element-wise product and their matrix product (using both @ and np.dot).

In [62]:
# Write your code here
a = np.arange(4).reshape(2,2)
b = np.arange(3,7).reshape(2,2)
print(a*b)
print(a@b)

[[ 0  4]
 [10 18]]
[[ 5  6]
 [21 26]]


**Q14.2** Print the transpose of the first matrix.

In [63]:
# Write your code here
print(a.T)

[[0 2]
 [1 3]]


---
## CRUD Operations on Arrays

_Create, Read, Update, Delete/Insert — arrays are fixed-size, so delete/insert return a new array rather than modifying in place._


## 15. CRUD — Create & Read

_Create = `np.array()`/creation helpers | Read = indexing & slicing_


**Q15.1** Create a 1D array of 8 integers and a 2D array of shape (3,3).

In [76]:
# Write your code here
a = np.array([1,2,3,4,3,56,7,4])
lis = np.arange(9).reshape(3,3)
lis2 = np.arange(4).reshape(2,2)
print(a,lis)


[ 1  2  3  4  3 56  7  4] [[0 1 2]
 [3 4 5]
 [6 7 8]]


**Q15.2** Read the element at index 3 from the 1D array, and the middle row from the 2D array.

In [78]:
# Write your code here
print(a[3])
print(lis2[0])


4
[0 1]


## 16. CRUD — Update

_`arr[i] = val` or `arr[slice] = val` → updates values directly (arrays are mutable)_


**Q16.1** Update index 2 of your 1D array to 100.

In [80]:
# Write your code here
a[2] = 100
print(a)


[  1   2 100   4   3  56   7   4]


**Q16.2** Update the entire second row of your 2D array to [0, 0, 0].

In [83]:
# Write your code here
lis2[1:2]= [0,0]

## 17. CRUD — Delete & Insert

_`np.delete(arr, idx, axis=)` → remove & return new array | `np.insert(arr, idx, val)` → insert value | `np.append(arr, val)` → add at the end_


**Q17.1** Delete the element at index 0 from your 1D array (store as a new variable).

In [88]:
# Write your code here
print(a)
np.delete(a,0)

[  1   2 100   4   3  56   7   4]


array([  2, 100,   4,   3,  56,   7,   4])

**Q17.2** Delete the last column from your 2D array.

In [87]:
# Write your code here
np.delete(lis,2,axis=0)

array([[0, 1, 2],
       [3, 4, 5]])

**Q17.3** Use np.append to add 99 to the end of your 1D array, and np.insert to insert 50 at index 1.

In [93]:
# Write your code here
a = np.append(a,99)
print(a)
a = np.insert(a,1,50)
print(a)


[  1  50   2 100   4   3  56   7   4  99  99  99  99]
[  1  50  50   2 100   4   3  56   7   4  99  99  99  99]


## 18. Combined Practice

_No new functions — just combining what's covered above_


**Q18.1** Create a 5x5 array (1-25), extract its center 3x3 block, then find the row-wise sum of that block.

In [95]:
# Write your code here
a = np.arange(1,26).reshape(5,5)
b = a[1:4, 1:4]
print(b.sum(axis=0))
print(b.sum(axis=1))

[36 39 42]
[24 39 54]


**Q18.2** Create two 1D int arrays, stack them with vstack, add 0.5 to the result and check the dtype coercion.

In [102]:
# Write your code here
a = np.arange(2,8)
b = np.arange(6)
c = np.vstack((a,b))
c = np.append(c, 0.5)
print(c.dtype)


float64


**Q18.3** Create a 4x4 matrix with np.diag() using diagonal values 2,4,6,8, then find its transpose.

In [105]:
# Write your code here
a = np.diag((2,4,6,8))
print(a.T)

[[2 0 0 0]
 [0 4 0 0]
 [0 0 6 0]
 [0 0 0 8]]
